---
# tasks file for nfs
- name: Create directory for NFS
  file:
    path: /srv/nfs
    state: directory

- name: Enable and start NFS service
  systemd:
    name: nfs-server
    state: started
    enabled: yes
    masked: no

- name: Add master to /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  with_items: "{{ groups.master }}"

- name: Add workers to /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  with_items: "{{ groups.workers }}"
  
- name: Reload configuration /etc/exports to apply the new configuration
  shell: |
    exportfs -r
    exportfs -s
    
- name: Firewall rules for the for the service to be accessible
  shell: |
    firewall-cmd --permanent --add-service=nfs
    firewall-cmd --permanent --add-service=rpc-bind
    firewall-cmd --permanent --add-service=mountd
    
- name: Restart Firewalld service
  systemd:
    name: firewalld
    state: restarted
