---
# tasks file for common

- name: "Installing Required Packages"
  package:
      name:
      - iproute-tc
      - net-tools
      - wget
      - nfs-utils
      - rpcbind
      - chrony
      - python3
      - nfs4-acl-tools
      state: present

- name: Disable SWAP 
  shell: |
       swapoff -a
       
- name: Disable SWAP in fstab 
  lineinfile:
     path: /etc/fstab
     regexp: 'swap'
     state: absent
       
- name: Disable SElinux
  selinux:
    state: disabled
  become: yes

- name: Enable Firewalld
  service:
    name: firewalld
    enabled: yes
    state: started
    
- name: Enable kernel module br_netfilter
  modprobe:
    name: br_netfilter
    state: present
  become: yes

- name: Enable masquerade public zone
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: public
  become: yes

- name: Configuring AllowZoneDrifting=no to firewalld
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting='
    line: "AllowZoneDrifting=no"
    state: present
  become: yes
  
- name: Enable 8285 port udp protocol
  firewalld:
    port: 8285/udp
    permanent: true
    state: enabled
  become: yes
  
- name: Enable 8472 port udp protocol
  firewalld:
    port: 8472/udp
    permanent: true
    state: enabled
  become: yes
  
- name: Install Chrony (Red Hat/Centos)
  dnf:
    name: chrony
    state: present
  become: yes

- name: Configuring timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid
  become: yes
  
- name: Enable Chronyd service (Red Hat)
  systemd:
    name: chronyd
    state: started
    enabled: yes
    masked: no
  become: yes
  
- name: "Configuing Kubernetes repository"
  yum_repository:
      name: kubernetes
      description: "Kubernetes"
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude: kubelet kubeadm kubectl

- name: "Install kubernetes"
  yum:
      name: [ 'kubectl', 'kubeadm', 'kubelet' ]
      state: present
      disable_excludes: kubernetes

- name: Add docker repository for centos
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes
      

- name: Install Docker
  package:
      name: docker-ce
      state: latest
  become: yes
  
- name: "Configuring the Ip tables "
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: "Starting Kubelet Service"
  service:
      name: "kubelet"
      state: started
      enabled: yes
      
- name: Confuring the docker daemon.json file
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }
    
- name: "Pulling the config images"
  shell: kubeadm config images pull
 
- name: "Restarting the docker service"
  service:
     name: docker
     state: restarted
     
- name: "Refreshing sysctl"
  shell: "sysctl --system"
