apiVersion: apps/v1
kind: Deployment
Namespace: test-ansible
metadata:    
  name: nginx-deployment  
  labels:
     app: nginx-httpd 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx-httpd  
  template:
    metadata:
      labels:
        app: nginx-httpd  
    spec:
      containers:
      - name: nginx-httpd 
        image: nginx:1.14.2
        ports:
        - containerPort: 80
