apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-deployment
  namespace: tutorial
  labels:
    app: tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial
  template:
    metadata:
      labels:
        app: tutorial
    spec:
      containers:
      - name: tutorial
        image: docker/getting-started
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1 

---
apiVersion: v1
kind: Service
metadata:
    name: tutorial-service
    namespace: tutorial
spec:
    selector:
      app: tutorial
    ports:
    - name: http
      protocol: TCP
      port: 80 # puerto en el que escucha el servicio
      targetPort: 80 # puerto en el que escucha el contenedor