apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
      run: load-balancer
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        run: load-balancer
    spec:
      containers:
      - name: nginxWebServer
        image: nginx:1.16.1
        ports:
        - containerPort: 80
          protocol: TCP