apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-routed
  namespace: nginx-routed
  labels:
    app: nginx-routed
spec:
  selector:
    matchLabels:
      app: nginx-routed
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-routed
    spec:
      containers:
      - name: nginx-routed
        image: nginx:1.16.1
        ports:
        - containerPort: 80