apiVersion: apps/v1
kind: Deployment
metadata:
  name: game2048_deployment
  labels:
    app: game2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game2048
  template:
    metadata:
      labels:
        app: game2048
    spec:
      containers:
      - name: game2048
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1 

---
apiVersion: v1
kind: Service
metadata:
    name: game2048-service
    annotations:
      haproxy.org/check: "enabled"
      haproxy.org/forwarded-for: "enabled"
      haproxy.org/load-balance: "roundrobin"
spec:
    selector:
      app: game2048
    ports:
    - name: http
      protocol: TCP
      port: 80 # puerto en el que escucha el servicio
      targetPort: 80 # puerto en el que escucha el contenedor