apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: cvillar.unir.k8
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-deployment
          servicePort: 8080