apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game2048-ingress
  annotations:
    haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: cvillar.unir.cp2
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: game2048-service
            port:
              number: 80