apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: game
spec:
  rules:
  - host: cvillar.unir.cp2
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: game-service
            port:
              number: 80