apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutorial-ingress
  namespace: tutorial
  labels:
    app: tutorial
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: cvillar.unir.cp2
    http:
      paths:
      - path: /tutorial
        pathType: "Prefix"
        backend:
          service: 
            name: tutorial-service
            port:
              number: 80