apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: cvillar.unir
    http:
      paths:
      - path: /app_example
        backend:
          service: 
            name: ginx-service
            port:
              number: 8081