apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutorial-ingress
  namespace: tutorial
spec:
  rules:
  - host: cvillar.unir.cp2
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: tutorial-service
            port:
              number: 80