apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: game
  labels:
    app: game
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: cvillar.unir.cp2
    http:
      paths:
      - path: /game
        pathType: "Prefix"
        backend:
          service: 
            name: game-service
            port:
              number: 80