apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todolist-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: cvillar.unir.cp2
    http:
      paths:
      - path: /todolist
        pathType: Prefix
        backend:
          service: 
            name: todolist-service
            port:
              number: 80