apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: cvillar.unir
    http:
      paths:
      - path: /app_example
        backend:
          serviceName: nginx-service
          servicePort: 8081