apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: tutorial
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /srv/nfs
    server: 10.0.1.10