---
# tasks file for app

- name: Copy deployment files to master
  copy:
      src: "{{ item }}"
      dest: "/root/{{ item }}"
      mode: 0777
  with_items:
   - "{{ files }}"

- name: Enable dynamic provisioning
  shell: "kubectl apply -f /root/storage.yml"

- name: Create namespace
  shell: "kubectl create namespace tutorial"

- name: Deploy the files
  shell: "kubectl apply -f /root/{{ item }}"
  register: deploy
  with_items:
    - "{{ files }}"

- name: Show deployment results
  debug:
    msg: "{{item.stdout_lines }}"
  with_items:
    - "{{ deploy.results }}"
