---
# tasks file for app
- name: Create namespace
  kubernetes.core.k8s:
    name: test-ansible
    api_version: v1
    kind: Namespace
    state: present    
    
- name: Copy deployment and pod file to master
  become: yes
  copy:
     src: "{{ item }}"
     dest: "/tmp/{{ item }}"
     mode: 0777
     with_items:
       - "{{ files }}"

- name: Create pod
  kubernetes.core.k8s:
     state: present      
     namespace: test-ansible  
     src: /tmp/pod.yaml

- name: Get the existing Pods in the kubernetes cluster
  kubernetes.core.k8s:
    api_version: v1
    kind: pod
    name: nginx
    namespace: test-ansible
    register: web_service

# Creating a Kubernetes deployment in test-ansible using file stored locally
- name: Create a kubernetes deployment
  kubernetes.core.k8s:
    state: present            
    namespace: test-ansible 
    src: /tmp/deployment.yaml