---
# tasks file for app

- name: Copy deployment file to master
  copy:
      src: "{{ item }}"
      dest: "/root/{{ item }}"
      mode: 0777
  with_items:
   - "{{ files }}"
   
- name: Deploy deployment.yml file nginx
  shell: "kubectl apply -f /root/{{ item }}"
  register: deploy
  with_items:
    - "{{ files }}"

- name: Show deployment results
  debug:
    msg: "{{item.stdout_lines }}"
  with_items:
    - "{{ deploy.results }}"


- name: Service object that exposes the deployment
  shell: "kubectl expose deployment nginx-deployment --type=NodePort --name=nginx-service"
  register: service

- name: Display information about the Service
  shell: "kubectl describe services nginx-service"
  register: information   
