---
# tasks file for app

- name: Copy deployment files to master
  copy:
      src: "{{ item }}"
      dest: "/root/{{ item }}"
      mode: 0777
  with_items:
   - "{{ files }}"
   
- name: Create namespace
  shell: "kubectl create namespace nginx-routed"
  register: namespace

- name: Deploy the files
  shell: "kubectl apply -f /root/{{ item }}"
  register: deploy
  with_items:
    - "{{ files }}"

- name: Show deployment results
  debug:
    msg: "{{item.stdout_lines }}"
  with_items:
    - "{{ deploy.results }}"

- name: Service object that exposes the deployment
  command: "kubectl expose deployment nginx-deployment --name=nginx-service --port=80 --target-Port=80"
  register: service

- name: Display information about the Service
  command: "kubectl describe services nginx-service"
  register: information
- debug:
    msg: "{{information.stdout}}"
