---
# tasks file for kubenodes

- name: Enable firewall ports workers
  firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
      - "{{ Firewall_ports_workers}}"
  
- name: Restart Firewalld service
  systemd:
    name: firewalld
    state: restarted
  
- name: Copy join command from Ansiblehost to the worker nodes.
  copy:
      src: /tmp/join_token
      dest: /tmp/join_token
      mode: 0777
       
- name: Join the Worker nodes to the cluster.
  shell: /tmp/join_token
  register: joined_or_not
