---
# tasks file for kubenodes

- name: Enable 10250 port TCP protocol
  firewalld:
    port: 10250/TCP
    permanent: true
    zone: public
    state: enabled
  become: yes
  
- name: Enable ports range 30000-32767 tcp protocol to join kubernetes cluster
  firewalld:
    port: 30000-32767/tcp
    permanent: true
    zone: public
    state: enabled
  become: yes
  
- name: Restaet Firewalld service
  systemd:
    name: firewalld
    state: restarted
  become: yes
  
- name: Copy join command from Ansiblehost to the worker nodes.
  become: yes
  copy:
      src: /tmp/join_token
      dest: /tmp/join_token
      mode: 0777
       
- name: Join the Worker nodes to the cluster.
  become: yes
  shell: /tmp/join_token
  register: joined_or_not
