- hosts: all
  become: true
  tasks:
    - name: Common tasks
      include_role:
        name: common

- hosts: master
  tasks:
    - name: Configuring master
      include_role:
        name: kubemaster

- hosts: workers
  tasks:
    - name: Configuring workers
      include_role:
        name: kubenodes
