---
# tasks file for kubemaster

- name: "Initializing the Kubernetes cluster on Master Node"
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all"
  ignore_errors: True

- name: "Configuration Files Setup"
  file:
    path: "$HOME/.kube"
    state: directory
    
- name: "Copying Configuration File"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: Change kubeconfig file permission
  file:
    path: $HOME/.kube/config 
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: "Downloading CNI Plugin"
  command: "kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  ignore_errors: True

- name: Install Ingress Controller
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml
    
- name: "Create Join Token"
  command: "kubeadm token create --print-join-command"
  register: join_token
  ignore_errors: True
- debug:
        msg: "{{join_token.stdout}}"
        
- name: Copy join command to local file.
  become: yes
  local_action: copy content="{{ join_token.stdout_lines[0] }}" dest="/tmp/join_token" mode=0777
